---
#- name: Install the libselinux-python package [RedHat]
#  dnf: 
#    name: python-selinux 
#    state: present
#  when: ansible_os_family == 'RedHat'

- name: Disable SELinux at next reboot
  selinux:
    state: disabled
  when: ansible_os_family == 'RedHat'

- name: Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false
  when: ansible_os_family == 'RedHat'
...
